source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKLThreadSafeMutableCollection_Example', :exclusive => true do
  pod "JKLThreadSafeMutableCollection", :path => "../"
end

target 'JKLThreadSafeMutableCollection_Tests', :exclusive => true do
  pod "JKLThreadSafeMutableCollection", :path => "../"

  
end
